[package]
name = "desktopbg"
version = "0.2.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.8", features = ["preserve_order"] }
walkdir = "2.4"
wallpaper = "3.2"
